import { createHash } from 'node:crypto';
import { mkdir, readFile, readdir, rm, writeFile, cp } from 'node:fs/promises';
import path from 'node:path';

const GENERATED_BANNER = '// AUTO-GENERATED by scripts/generate.mjs. Do not edit by hand.';
const GENERATED_TEXT = 'Generated by scripts/generate.mjs. Do not edit by hand.';

const pageKey = (value) => String(value).toUpperCase();
const moduleKey = (value) => String(value).toLowerCase();

export async function readJson(filePath) {
  return JSON.parse(await readFile(filePath, 'utf8'));
}

export async function writeJson(filePath, value) {
  await mkdir(path.dirname(filePath), { recursive: true });
  await writeFile(filePath, `${JSON.stringify(value, null, 2)}\n`);
}

export async function listTenantIds(rootDir = process.cwd()) {
  const dir = path.join(rootDir, 'schemas/tenants');
  const entries = await readdir(dir, { withFileTypes: true });
  return entries
    .filter((entry) => entry.isFile() && entry.name.endsWith('.json'))
    .map((entry) => path.basename(entry.name, '.json'))
    .sort();
}

function stableStringify(value) {
  if (Array.isArray(value)) return `[${value.map(stableStringify).join(',')}]`;
  if (value && typeof value === 'object') {
    return `{${Object.keys(value).sort().map((key) => `${JSON.stringify(key)}:${stableStringify(value[key])}`).join(',')}}`;
  }
  return JSON.stringify(value);
}

function hashConfig(value) {
  return createHash('sha256').update(stableStringify(value)).digest('hex').slice(0, 16);
}

function assert(condition, message) {
  if (!condition) throw new Error(message);
}

function indexBy(items, getId, label) {
  const map = new Map();
  for (const item of items) {
    const id = getId(item);
    if (map.has(id)) throw new Error(`${label} has duplicate id: ${id}`);
    map.set(id, item);
  }
  return map;
}

function normalizeComponentImport(componentPath) {
  if (componentPath.startsWith('src/')) return componentPath.replace('src/', '../');
  if (componentPath.startsWith('@/')) return componentPath.replace('@/', '../');
  return componentPath;
}

function jsonModuleExport(name, value) {
  return `${GENERATED_BANNER}\n\nexport const ${name} = ${JSON.stringify(value, null, 2)};\nexport default ${name};\n`;
}

export async function loadInputs(rootDir, tenantId) {
  const [pagesCatalog, modulesCatalog, pagesBase, manifestBase, tenant] = await Promise.all([
    readJson(path.join(rootDir, 'schemas/catalog/pages.json')),
    readJson(path.join(rootDir, 'schemas/catalog/modules.json')),
    readJson(path.join(rootDir, 'pages.base.json')),
    readJson(path.join(rootDir, 'manifest.base.json')),
    readJson(path.join(rootDir, `schemas/tenants/${tenantId}.json`))
  ]);
  return { pagesCatalog, modulesCatalog, pagesBase, manifestBase, tenant };
}

export function buildTenantArtifacts(inputs) {
  const { pagesCatalog, modulesCatalog, pagesBase, manifestBase, tenant } = inputs;
  const normalizedPages = pagesCatalog.pages.map((page) => ({
    ...page,
    id: pageKey(page.id),
    route: page.route ?? page.path,
    component: page.component ?? `src/pages/${String(page.id).toLowerCase()}/index.vue`
  }));
  const normalizedModules = modulesCatalog.modules.map((module) => ({
    ...module,
    id: moduleKey(module.id),
    name: module.name ?? module.componentRef,
    component: module.component ?? module.componentPath ?? `src/modules/${moduleKey(module.id)}/index.vue`
  }));
  const pageCatalog = indexBy(normalizedPages, (page) => page.id, 'page catalog');
  const moduleCatalog = indexBy(normalizedModules, (module) => module.id, 'module catalog');
  const tenantPages = (tenant.pages ?? []).map((page) => ({ ...page, pageId: pageKey(page.pageId) }));
  const tenantPageIds = new Set(tenantPages.map((page) => page.pageId));

  assert(tenant.id, 'tenant.id is required');
  assert(tenant.schemaVersion, `tenant ${tenant.id} schemaVersion is required`);
  assert(tenant.platforms?.['mp-weixin']?.appid, `tenant ${tenant.id} platforms.mp-weixin.appid is required`);
  assert(tenantPages.length > 0, `tenant ${tenant.id} must declare pages`);
  assert(tenantPageIds.size === tenantPages.length, `tenant ${tenant.id} pages cannot repeat pageId`);

  for (const page of tenantPages) {
    assert(pageCatalog.has(page.pageId), `tenant ${tenant.id} page ${page.pageId} is not in catalog`);
  }

  const routes = tenantPages.map((page) => {
    const catalogPage = pageCatalog.get(page.pageId);
    return {
      pageId: page.pageId,
      path: catalogPage.route,
      type: catalogPage.type,
      title: page.title ?? catalogPage.defaultTitle,
      isTab: page.isTab ?? true,
      component: catalogPage.component
    };
  });
  assert(new Set(routes.map((route) => route.path)).size === routes.length, `tenant ${tenant.id} page paths must be unique`);

  const tabs = (tenant.tabs ?? [])
    .map((tab, index) => ({ ...tab, pageId: pageKey(tab.pageId), order: tab.order ?? index + 1 }))
    .sort((left, right) => left.order - right.order);
  assert(tabs.length > 0, `tenant ${tenant.id} must declare tabs`);
  assert(tabs.length <= 5, `tenant ${tenant.id} tab count exceeds mp-weixin limit`);
  assert(new Set(tabs.map((tab) => tab.id)).size === tabs.length, `tenant ${tenant.id} tabs cannot repeat id`);

  for (const tab of tabs) {
    assert(tenantPageIds.has(tab.pageId), `tenant ${tenant.id} tab ${tab.id} references missing page ${tab.pageId}`);
    const route = routes.find((candidate) => candidate.pageId === tab.pageId);
    assert(route?.isTab, `tenant ${tenant.id} tab ${tab.id} references non-tab page ${tab.pageId}`);
  }

  const layoutB = tenant.layouts?.B ?? tenant.layouts?.b;
  assert(layoutB?.layoutType === 'flow', `tenant ${tenant.id} must declare flow layout for page B`);
  assert(tenantPageIds.has('B'), `tenant ${tenant.id} flow layout requires page B`);

  const moduleIds = layoutB.modules.map((entry) => moduleKey(entry.moduleId));
  assert(new Set(moduleIds).size === moduleIds.length, `tenant ${tenant.id} page B modules cannot repeat`);
  for (const moduleId of moduleIds) {
    assert(moduleCatalog.has(moduleId), `tenant ${tenant.id} module ${moduleId} is not in catalog`);
    if (tenant.allowedModules) {
      assert(tenant.allowedModules.map(moduleKey).includes(moduleId), `tenant ${tenant.id} module ${moduleId} is not allowed`);
    }
  }

  const configHash = hashConfig({ pagesCatalog, modulesCatalog, tenant });
  const generated = GENERATED_TEXT;
  const selectedColor = tenant.theme.tabSelectedColor ?? tenant.theme.selectedColor;
  const pagesJson = {
    _generated: generated,
    _tenantId: tenant.id,
    _configHash: configHash,
    ...pagesBase,
    pages: routes.map((route) => ({ path: route.path, style: { navigationBarTitleText: route.title } })),
    tabBar: {
      color: tenant.theme.tabColor,
      selectedColor,
      backgroundColor: '#ffffff',
      list: tabs.map((tab) => {
        const route = routes.find((candidate) => candidate.pageId === tab.pageId);
        return {
          pagePath: route.path,
          text: tab.label,
          iconPath: tab.iconPath ?? tab.icon,
          selectedIconPath: tab.selectedIconPath ?? tab.selectedIcon
        };
      })
    }
  };

  const manifestJson = {
    _generated: generated,
    _tenantId: tenant.id,
    _configHash: configHash,
    ...manifestBase,
    name: tenant.displayName,
    description: `${tenant.displayName} generated from ${tenant.id}@${tenant.schemaVersion}`,
    versionName: tenant.platforms['mp-weixin'].versionName ?? manifestBase.versionName,
    'mp-weixin': {
      ...manifestBase['mp-weixin'],
      ...(tenant.platforms['mp-weixin'] ?? {})
    }
  };

  const routeConfig = {
    generated,
    tenantId: tenant.id,
    configHash,
    routes: routes.map((route) => ({
      pageId: route.pageId,
      path: route.path,
      type: route.type,
      title: route.title,
      inTabBar: route.isTab,
      component: route.component
    })),
    tabRoutes: tabs.map((tab) => {
      const route = routes.find((candidate) => candidate.pageId === tab.pageId);
      return { tabId: tab.id, pageId: tab.pageId, path: route.path, label: tab.label };
    })
  };

  const pageBModules = layoutB.modules.map((entry, index) => {
    const moduleId = moduleKey(entry.moduleId);
    const catalogModule = moduleCatalog.get(moduleId);
    return {
      order: index + 1,
      moduleId,
      componentName: catalogModule.name,
      componentPath: catalogModule.component,
      props: entry.props ?? {},
      dataSource: entry.dataSource ?? null
    };
  });

  const moduleRegistry = { generated, tenantId: tenant.id, configHash, pageModules: { B: pageBModules } };
  const runtimeConfig = {
    generated,
    tenantId: tenant.id,
    name: tenant.name,
    displayName: tenant.displayName,
    schemaVersion: tenant.schemaVersion,
    releaseChannel: tenant.releaseChannel,
    configHash,
    generatedAt: new Date(0).toISOString(),
    theme: tenant.theme,
    runtime: tenant.runtime,
    platform: { target: 'mp-weixin', appid: tenant.platforms['mp-weixin'].appid },
    pages: routes,
    tabs: tabs.map((tab) => ({ ...tab, route: routes.find((route) => route.pageId === tab.pageId).path })),
    layouts: {
      B: {
        layoutType: 'flow',
        modules: pageBModules.map(({ order, moduleId, props, dataSource }) => ({ order, moduleId, props, dataSource }))
      }
    }
  };
  const metadata = {
    generated,
    tenantId: tenant.id,
    schemaVersion: tenant.schemaVersion,
    configHash,
    platform: 'mp-weixin',
    pages: routes.map((route) => route.pageId),
    tabs: tabs.map((tab) => tab.label),
    pageBModules: moduleIds
  };

  const routeConstants = `${GENERATED_BANNER}\n\nexport const tenantId = ${JSON.stringify(tenant.id)};\nexport const configHash = ${JSON.stringify(configHash)};\nexport const routes = ${JSON.stringify(routeConfig.routes, null, 2)};\nexport const tabRoutes = ${JSON.stringify(routeConfig.tabRoutes, null, 2)};\nexport const pagePathById = Object.freeze(Object.fromEntries(routes.map((route) => [route.pageId, route.path])));\n`;
  const registryImports = pageBModules.map((module) => `import ${module.componentName} from '${normalizeComponentImport(module.componentPath)}';`).join('\n');
  const moduleRegistryJs = `${GENERATED_BANNER}\n${registryImports}\n\nexport const tenantId = ${JSON.stringify(tenant.id)};\nexport const configHash = ${JSON.stringify(configHash)};\nexport const moduleRegistry = Object.freeze([\n${pageBModules.map((module) => `  { id: ${JSON.stringify(module.moduleId)}, order: ${module.order}, component: ${module.componentName}, props: ${JSON.stringify(module.props)}, dataSource: ${JSON.stringify(module.dataSource)} }`).join(',\n')}\n]);\n\nexport function resolveModule(moduleId) {\n  return moduleRegistry.find((entry) => entry.id === moduleId);\n}\n`;
  const flowRendererBranches = pageBModules
    .map((module) => `      <${module.componentName} v-if="entry.moduleId === '${module.moduleId}'" v-bind="entry.props" :data-source="entry.dataSource" />`)
    .join('\n');
  const flowRendererVue = `<template>\n  <view>\n    <view class="module-card" v-for="entry in modules" :key="entry.moduleId">\n${flowRendererBranches}\n    </view>\n  </view>\n</template>\n\n<script>\nimport runtimeConfig from './tenant.js';\n${registryImports}\n\nexport default {\n  name: 'FlowPageBModules',\n  components: { ${pageBModules.map((module) => module.componentName).join(', ')} },\n  computed: {\n    modules() {\n      return runtimeConfig.layouts.B.modules;\n    }\n  }\n};\n</script>\n`;
  const runtimeJs = jsonModuleExport('runtimeConfig', runtimeConfig);

  return {
    tenant,
    configHash,
    pagesJson,
    manifestJson,
    routeConfig,
    moduleRegistry,
    runtimeConfig,
    metadata,
    generatedFiles: {
      'tenant.js': runtimeJs,
      'routes.js': routeConstants,
      'module-registry.js': moduleRegistryJs,
      'flow-page-b-modules.vue': flowRendererVue,
      'runtime-config.js': runtimeJs,
      'route-config.json': `${JSON.stringify(routeConfig, null, 2)}\n`,
      'module-registry.json': `${JSON.stringify(moduleRegistry, null, 2)}\n`,
      'runtime-config.json': `${JSON.stringify(runtimeConfig, null, 2)}\n`,
      'metadata.json': `${JSON.stringify(metadata, null, 2)}\n`
    }
  };
}

async function writeGeneratedDir(generatedDir, generatedFiles) {
  await rm(generatedDir, { recursive: true, force: true });
  await mkdir(generatedDir, { recursive: true });
  for (const [fileName, content] of Object.entries(generatedFiles)) {
    await writeFile(path.join(generatedDir, fileName), content);
  }
}

export async function generateTenant({ tenantId, rootDir = process.cwd(), writeRoot = true, snapshotRoot } = {}) {
  const selectedTenant = tenantId ?? process.env.TENANT ?? 'app1';
  const inputs = await loadInputs(rootDir, selectedTenant);
  const artifacts = buildTenantArtifacts(inputs);

  if (writeRoot) {
    await writeJson(path.join(rootDir, 'pages.json'), artifacts.pagesJson);
    await writeJson(path.join(rootDir, 'manifest.json'), artifacts.manifestJson);
    await writeJson(path.join(rootDir, 'src/pages.json'), artifacts.pagesJson);
    await writeJson(path.join(rootDir, 'src/manifest.json'), artifacts.manifestJson);
    await writeGeneratedDir(path.join(rootDir, 'src/generated'), artifacts.generatedFiles);
  }

  const snapshotDir = snapshotRoot ?? path.join(rootDir, 'dist/tenants', selectedTenant);
  await rm(snapshotDir, { recursive: true, force: true });
  await mkdir(snapshotDir, { recursive: true });
  await writeJson(path.join(snapshotDir, 'pages.json'), artifacts.pagesJson);
  await writeJson(path.join(snapshotDir, 'manifest.json'), artifacts.manifestJson);
  await writeGeneratedDir(path.join(snapshotDir, 'generated'), artifacts.generatedFiles);

  return { ...artifacts, snapshotDir };
}

export async function copyTenantWorkspace(rootDir, tenantId, workspaceDir) {
  await rm(workspaceDir, { recursive: true, force: true });
  await mkdir(workspaceDir, { recursive: true });
  for (const entry of ['src', 'schemas', 'pages.base.json', 'manifest.base.json', 'package.json']) {
    await cp(path.join(rootDir, entry), path.join(workspaceDir, entry), { recursive: true });
  }
  return generateTenant({ tenantId, rootDir: workspaceDir, writeRoot: true, snapshotRoot: path.join(workspaceDir, 'dist/tenants', tenantId) });
}
