import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, '..');
const GENERATED_BANNER = 'Generated by scripts/generate-tenant.mjs. Do not edit by hand.';

function stableStringify(value) {
  if (Array.isArray(value)) {
    return `[${value.map(stableStringify).join(',')}]`;
  }
  if (value && typeof value === 'object') {
    return `{${Object.keys(value)
      .sort()
      .map((key) => `${JSON.stringify(key)}:${stableStringify(value[key])}`)
      .join(',')}}`;
  }
  return JSON.stringify(value);
}

function hashConfig(value) {
  return createHash('sha256').update(stableStringify(value)).digest('hex').slice(0, 16);
}

async function readJson(relativePath) {
  return JSON.parse(await readFile(path.join(rootDir, relativePath), 'utf8'));
}

async function writeJson(relativePath, value) {
  const filePath = path.join(rootDir, relativePath);
  await mkdir(path.dirname(filePath), { recursive: true });
  await writeFile(filePath, `${JSON.stringify(value, null, 2)}\n`);
}

async function writeText(relativePath, value) {
  const filePath = path.join(rootDir, relativePath);
  await mkdir(path.dirname(filePath), { recursive: true });
  await writeFile(filePath, `${value.trimEnd()}\n`);
}

function indexById(items, label) {
  const index = new Map();
  for (const item of items) {
    if (index.has(item.id)) {
      throw new Error(`Duplicate ${label} id: ${item.id}`);
    }
    index.set(item.id, item);
  }
  return index;
}

function assertUnique(values, label) {
  const seen = new Set();
  for (const value of values) {
    if (seen.has(value)) {
      throw new Error(`Duplicate ${label}: ${value}`);
    }
    seen.add(value);
  }
}

function buildTenantArtifacts(catalogPages, catalogModules, tenant) {
  const pagesById = indexById(catalogPages.pages, 'page');
  const modulesById = indexById(catalogModules.modules, 'module');
  const tenantPageIds = tenant.pages.map((page) => page.pageId);
  assertUnique(tenantPageIds, `${tenant.id} pageId`);
  assertUnique(catalogPages.pages.map((page) => page.path), 'catalog page path');

  for (const tab of tenant.tabs) {
    if (!tenantPageIds.includes(tab.pageId)) {
      throw new Error(`${tenant.id} tab ${tab.id} references missing page ${tab.pageId}`);
    }
  }
  if (tenant.tabs.length < 2 || tenant.tabs.length > 5) {
    throw new Error(`${tenant.id} tab count must fit small-program native tabBar constraints`);
  }

  const selectedPages = tenant.pages.map((tenantPage) => {
    const catalogPage = pagesById.get(tenantPage.pageId);
    if (!catalogPage) {
      throw new Error(`${tenant.id} references unknown page ${tenantPage.pageId}`);
    }
    return {
      pageId: tenantPage.pageId,
      path: catalogPage.path,
      type: catalogPage.type,
      style: {
        navigationBarTitleText: tenantPage.title || catalogPage.defaultTitle
      }
    };
  });

  const flowLayout = tenant.layouts?.b;
  if (!flowLayout || flowLayout.layoutType !== 'flow') {
    throw new Error(`${tenant.id} must define a flow layout for page b`);
  }
  const moduleIds = flowLayout.modules.map((module) => module.moduleId);
  assertUnique(moduleIds, `${tenant.id} page b moduleId`);
  for (const moduleId of moduleIds) {
    if (!modulesById.has(moduleId)) {
      throw new Error(`${tenant.id} page b references unknown module ${moduleId}`);
    }
  }

  const hashInput = {
    tenant,
    selectedPages,
    moduleIds
  };
  const configHash = hashConfig(hashInput);

  const pagesJson = {
    _generated: GENERATED_BANNER,
    _tenantId: tenant.id,
    _configHash: configHash,
    pages: selectedPages.map((page) => ({
      path: page.path,
      style: page.style
    })),
    globalStyle: {
      navigationBarTextStyle: 'black',
      navigationBarTitleText: tenant.displayName,
      navigationBarBackgroundColor: tenant.theme.backgroundColor,
      backgroundColor: tenant.theme.backgroundColor
    },
    tabBar: {
      color: tenant.theme.tabColor,
      selectedColor: tenant.theme.selectedColor,
      backgroundColor: '#ffffff',
      list: tenant.tabs.map((tab) => {
        const page = selectedPages.find((candidate) => candidate.pageId === tab.pageId);
        return {
          text: tab.label,
          pagePath: page.path,
          iconPath: tab.iconPath,
          selectedIconPath: tab.selectedIconPath
        };
      })
    }
  };

  const manifestJson = {
    _generated: GENERATED_BANNER,
    _tenantId: tenant.id,
    _configHash: configHash,
    name: tenant.name,
    appid: `__UNI__${tenant.id.toUpperCase()}`,
    description: `${tenant.displayName} generated tenant shell`,
    versionName: tenant.schemaVersion,
    versionCode: tenant.schemaVersion.replace(/\D/g, '').slice(0, 9),
    transformPx: false,
    'mp-weixin': {
      appid: tenant.platforms['mp-weixin'].appid,
      setting: {
        urlCheck: false,
        es6: true,
        minified: true
      },
      usingComponents: true
    }
  };

  const routeConfig = {
    generated: GENERATED_BANNER,
    tenantId: tenant.id,
    configHash,
    routes: selectedPages.map((page) => ({
      pageId: page.pageId,
      path: `/${page.path}`,
      type: page.type,
      title: page.style.navigationBarTitleText,
      inTabBar: tenant.tabs.some((tab) => tab.pageId === page.pageId)
    })),
    tabRoutes: tenant.tabs.map((tab) => {
      const page = selectedPages.find((candidate) => candidate.pageId === tab.pageId);
      return {
        tabId: tab.id,
        pageId: tab.pageId,
        path: `/${page.path}`,
        label: tab.label
      };
    })
  };

  const moduleRegistry = {
    generated: GENERATED_BANNER,
    tenantId: tenant.id,
    configHash,
    pageModules: {
      b: flowLayout.modules.map((module, order) => {
        const catalogModule = modulesById.get(module.moduleId);
        return {
          moduleId: module.moduleId,
          order,
          componentRef: catalogModule.componentRef,
          componentPath: catalogModule.componentPath,
          props: module.props || {},
          dataSource: module.dataSource || null
        };
      })
    }
  };

  const runtimeConfig = {
    generated: GENERATED_BANNER,
    tenantId: tenant.id,
    tenantName: tenant.name,
    displayName: tenant.displayName,
    schemaVersion: tenant.schemaVersion,
    releaseChannel: tenant.releaseChannel,
    configHash,
    theme: tenant.theme,
    platform: {
      target: 'mp-weixin',
      appid: tenant.platforms['mp-weixin'].appid
    },
    apiBaseUrl: tenant.runtime.apiBaseUrl,
    featureFlags: tenant.runtime.featureFlags,
    pages: routeConfig.routes,
    layouts: {
      b: {
        layoutType: 'flow',
        moduleOrder: moduleRegistry.pageModules.b.map((module) => module.moduleId)
      }
    }
  };

  return {
    pagesJson,
    manifestJson,
    routeConfig,
    moduleRegistry,
    runtimeConfig
  };
}

function moduleRegistryJs(moduleRegistry) {
  const imports = moduleRegistry.pageModules.b
    .map((module) => `import ${module.componentRef} from '${module.componentPath}';`)
    .join('\n');
  const registryRows = moduleRegistry.pageModules.b
    .map(
      (module) =>
        `  ${JSON.stringify(module.moduleId)}: { component: ${module.componentRef}, componentPath: ${JSON.stringify(module.componentPath)}, props: ${JSON.stringify(module.props)}, dataSource: ${JSON.stringify(module.dataSource)} }`
    )
    .join(',\n');
  return `// ${GENERATED_BANNER}\n${imports}\n\nexport const tenantId = ${JSON.stringify(moduleRegistry.tenantId)};\nexport const configHash = ${JSON.stringify(moduleRegistry.configHash)};\nexport const pageBModuleRegistry = {\n${registryRows}\n};\n\nexport const pageBModuleOrder = ${JSON.stringify(moduleRegistry.pageModules.b.map((module) => module.moduleId))};\n`;
}

function routeConfigJs(routeConfig) {
  return `// ${GENERATED_BANNER}\nexport const tenantId = ${JSON.stringify(routeConfig.tenantId)};\nexport const configHash = ${JSON.stringify(routeConfig.configHash)};\nexport const routes = ${JSON.stringify(routeConfig.routes, null, 2)};\nexport const tabRoutes = ${JSON.stringify(routeConfig.tabRoutes, null, 2)};\n`;
}

function runtimeConfigJs(runtimeConfig) {
  return `// ${GENERATED_BANNER}\nexport const runtimeConfig = ${JSON.stringify(runtimeConfig, null, 2)};\nexport default runtimeConfig;\n`;
}

export async function generateTenant(tenantId, { writeRoot = false } = {}) {
  const [catalogPages, catalogModules, tenant] = await Promise.all([
    readJson('schemas/catalog/pages.json'),
    readJson('schemas/catalog/modules.json'),
    readJson(`schemas/tenants/${tenantId}.json`)
  ]);
  const artifacts = buildTenantArtifacts(catalogPages, catalogModules, tenant);
  const tenantDir = `src/generated/tenants/${tenantId}`;
  await writeJson(`${tenantDir}/pages.json`, artifacts.pagesJson);
  await writeJson(`${tenantDir}/manifest.json`, artifacts.manifestJson);
  await writeJson(`${tenantDir}/route-config.json`, artifacts.routeConfig);
  await writeJson(`${tenantDir}/module-registry.json`, artifacts.moduleRegistry);
  await writeJson(`${tenantDir}/runtime-config.json`, artifacts.runtimeConfig);

  if (writeRoot) {
    await writeJson('pages.json', artifacts.pagesJson);
    await writeJson('manifest.json', artifacts.manifestJson);
    await writeJson('src/generated/route-config.json', artifacts.routeConfig);
    await writeJson('src/generated/module-registry.json', artifacts.moduleRegistry);
    await writeJson('src/generated/runtime-config.json', artifacts.runtimeConfig);
    await writeText('src/generated/routes.js', routeConfigJs(artifacts.routeConfig));
    await writeText('src/generated/module-registry.js', moduleRegistryJs(artifacts.moduleRegistry));
    await writeText('src/generated/runtime-config.js', runtimeConfigJs(artifacts.runtimeConfig));
  }
  return artifacts;
}

async function main() {
  const tenantIdsArg = process.argv[2] || 'app1,app2';
  const rootTenant = process.argv[3] || 'app1';
  const tenantIds = tenantIdsArg.split(',').map((tenantId) => tenantId.trim()).filter(Boolean);
  for (const tenantId of tenantIds) {
    await generateTenant(tenantId, { writeRoot: tenantId === rootTenant });
  }
}

if (import.meta.url === `file://${process.argv[1]}`) {
  main().catch((error) => {
    console.error(error);
    process.exit(1);
  });
}
